### ISSUE TITLE
Script erases /etc/fstab

### ISSUE THREAD

**Issue by ukasz** [rahulinux/compliance#2]
I think that changes in fstab should be made via tmp file, otherwise user can lost data.

$ cp /etc/fstab fstab
$ cat fstab | wc -l
10
$ awk '1;/\/tmp/{$4="nosuid,nodev,noexec";print}' fstab | column -t | wc -l
11
$ awk '1;/\/tmp/{$4="nosuid,nodev,noexec";print}' fstab | column -t > fstab
$ cat fstab | wc -l
0

On the other hand you should not use dd-mm-rr format to name backup files, this way previous backups are overwritten.

**Comment by rahulinux** [comment]
@ukasz  thanks for point me in the right direction 

So the we need to 1st make copy of original  to fstab.tmp then make changes in fstab.tmp and then overwritten in original fstab ? m I right ?

Here is script look like after changes, so once check and let me know.. 

```
 OK "Updating /etc/fstab for /tmp partition.."
                        Fstab='/etc/fstab.tmp'
                        [[ -f $Fstab ]] || cp  /etc/fstab  $Fstab
                        [[ -f /etc/fstab-bkp-$(date +%F)  ]] || cp /etc/fstab{,-bkp-$(date +%F)} >/dev/null 2>&1
                        awk '1;/\/tmp/{$4="nosuid,nodev,noexec";print}' $Fstab | column -t > $Fstab
                        sed -i '/\/tmp/{s/^/#/;:a;n;ba}' $Fstab
                        cat $Fstab  > /etc/fstab
                        mount -o remount /tmp
```

**Comment by rahulinux** [comment]
We've tested this script on CentOS 5 and Ubuntu 12.04 but haven't faced this issue, So kindly let us know what OS you are using.

**Comment by ukasz** [comment]
CentOS 6.4, I'll take a look at that script later today.

**Comment by ukasz** [comment]
As I showed earlier this line causes the problem, you're trying to read and write to the same file. When you use pipes output all programs may run concurently. I think you assumed that column -t waits for awk to end, but this does not work like that.
awk '1;/\/tmp/{$4="nosuid,nodev,noexec";print}' $Fstab | column -t > $Fstab
It should be more like  
awk '1;/\/tmp/{$4="nosuid,nodev,noexec";print}' $Fstab | column -t > $Fstab.tmp
But first you have to check whether $Fstab.tmp does not exist otherwise it will be a bit unsecure.

**Comment by rahulinux** [comment]
Hi ukasz,

issue 2# fstab, has been tested on RHEL 6.3 and fixed 
So kindly Once test updated script from your end and if everything is fine then you can mark this ticket as close.

--Rahul Patil

**Comment by rahulinux** [comment]
Hi ukasz,

looking forward to your reply.

**Comment by ukasz** [comment]
It's fixed now, thx.
