### ISSUE TITLE
Question about backups and configs modifications

### ISSUE THREAD

**Issue by rafis** [rahulinux/compliance#4]
Is this script have only one mode: it modifies all errors he finds? Can it work in mode which will just show mistakes in configuration without modifying anything, or can it make backups before modifying and ability to run revert to original configs?

**Comment by rahulinux** [comment]
>  it modifies all errors he finds?

No, it has Predefined configuration which it's place in respective files

>  Can it work in mode which will just show mistakes in configuration without modifying anything

No, but you are free to edit and run, instead of `sed`, use `echo sed` so it will only display 

> can it make backups before modifying

every file which going to edit will take as backup with `filename-bkp-$(date +%F)`

> ability to run revert to original configs?

No
